<?php
// $Id: watchdog.module,v 1.165.2.1 2007/01/23 19:07:33 dries Exp $

/**
 * @file
 * System monitoring and logging for administrators.
 *
 * The watchdog module monitors your site and keeps a list of
 * recorded events containing usage and performance data, errors,
 * warnings, and similar operational information.
 *
 * @see watchdog().
 */

function watchdog_help($section) {
  switch ($section) {
    case 'admin/help#watchdog':
    case 'admin/logs':
      include_once dirname(__FILE__).'/help.inc.php';
      return real_watchdog_help($section);
  }
}

/**
 * Implementation of hook_menu().
 */
function watchdog_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    include_once dirname(__FILE__).'/menu.inc.php';
    watchdog_menu_may_cache($items);
  }
  else {
    if (arg(0) == 'admin' && arg(1) == 'logs') {
      // Add the CSS for this module
      drupal_add_css(drupal_get_path('module', 'watchdog') .'/watchdog.css', 'module', 'all', FALSE);
    }
  }

  return $items;
}

function watchdog_cron() {
  include_once dirname(__FILE__).'/cron.inc.php';
  return real_watchdog_cron();
}

/**
 * Implementation of hook_user().
 */
function watchdog_user($op, &$edit, &$user) {
  if ($op == 'delete') {
    db_query('UPDATE {watchdog} SET uid = 0 WHERE uid = %d', $user->uid);
  }
}

function watchdog_overview() {
  include_once dirname(__FILE__).'/overview.inc.php';
  return real_watchdog_overview();
}

function watchdog_top($type) {
  include_once dirname(__FILE__).'/top.inc.php';
  return real_watchdog_top($type);
}

function watchdog_event($id) {
  include_once dirname(__FILE__).'/event.inc.php';
  return real_watchdog_event($id);
}
